default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: 123

development:
  <<: *default
  database: playlist-rails

test:
  <<: *default
  database: playlist-rails

production:
  <<: *default
  database: playlist-rails
